import hashlib
import os
import random
from PIL import Image
import datetime

class Utils: 
    def __init__(self) -> None:
        pass
    
    @staticmethod
    def image_metadata(image_dataset_directory: str, image_path: str, hashing_type: str, username: str, label: str) -> str: 
        """TODO docs 
        """ 
        metadata = {}
        #read the image, make sure it's not corrupted 
        try: 
            image = Image.open(image_path)
        
            metadata = {
                'username': username, 
                'label': label, 
                'hash_function': hashing_type, 
                'image_hash': Utils.compute_hash(image.tobytes(), hashing_type), 
                'image_dataset_directory': image_dataset_directory, 
                'image_path': image_path, 
                'image_name': os.path.splitext(os.path.basename(image_path))[0],
                'image_size_bytes': os.stat(image_path).st_size, 
                'image_dimensions': image.size, 
                'tag_date': str(datetime.datetime.now()), 
                'tag_date_unix': datetime.datetime.now().timestamp(), 
            }
            
        except Exception: 
            metadata = {
                'username': username, 
                'label': label, 
                'image_dataset_directory': image_dataset_directory, 
                'image_path': image_path, 
                'image_name': os.path.splitext(os.path.basename(image_path))[0], 
                'image_size_bytes': os.stat(image_path).st_size,
                'tag_date': str(datetime.datetime.now()), 
                'tag_date_unix': datetime.datetime.now().timestamp(), 
            } 

        return metadata
    
    @staticmethod
    def get_random_sample(source: list, sample_size: int = 16, seed: int = None) -> list: 
        """TODO document the method. 
        """
        
        #if the seed was specified by the user. 
        if seed is not None:         
            #define the seed generated by the user. 
            random.seed(seed)
        
        #return the random sample from the source with the specified sample size.
        return random.sample(source, min(sample_size , len(source)))
    
    @staticmethod
    def get_files_list(directory: str) -> list[str]: 
        """TODO document the method. 
        """
        return [{'url': file_name} for file_name in os.listdir(directory)]
    
    @staticmethod
    def compute_hash(object: bytes, hashing_type: str) -> str: 
        """TODO document the method. 
        """
        #make sure the received object is an instance of bytes. 
        assert isinstance(object, bytes)
        
        #Check the chosen hashing type. 
        if hashing_type == 'blake2b': 
            return hashlib.blake2b(object).hexdigest()
        elif hashing_type == 'sha256':
            return hashlib.sha256(object).hexdigest()
        else: 
            raise Exception("{} hashing type is not found only blake2b & sha256 are supported.")